from typing import Any, Protocol
from adcm.domain.models import RequirementBundle


class ContractForgePort(Protocol):
    async def next_requirements(self, known_values: dict[str, Any]) -> RequirementBundle: ...
    async def validate_partial(self, draft: dict[str, Any]) -> list[str]: ...
    async def validate_final(self, draft: dict[str, Any]) -> list[str]: ...
