from typing import Protocol
from adcm.domain.session.models import Session

class SessionRepositoryPort(Protocol):
    async def create(self, session: Session) -> Session: ...
    async def get(self, session_id: str) -> Session | None: ...
    async def save(self, session: Session) -> None: ...
